baseurl = "rlouden.netlify.com/"
DefaultContentLanguage = "en"
#DefaultContentLanguage = "ja"
title = "Upsupervised Learnings"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true


[Params]
  homeTitle = "Upsupervised Learnings"
  subtitle = "A blog to showcase my foray into analytics and data science"
  logo = "img/avatar.png"
  dateFormat = "April 20, 19"
  commit = false
  rss = false
  comments = false
  readingTime = false
  wordCount = false
  useHLJS = false
  socialShare = false
  delayDisqus = false
  showRelatedPosts = false


[Author]
  github = "Richyyl"
  twitter = "Richyyl"

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 3
