baseurl = ""
DefaultContentLanguage = "en"
#DefaultContentLanguage = "ja"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
title = "Upsupervised Learnings"
copyright = "Logo copyright of zen pencils"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true


[Params]
  homeTitle = "Upsupervised Learnings"
  subtitle = "A blog to showcase my foray into analytics and data science"
  date_format = "Mon, Jan 2, 2006"
  logo = "img/avatar.png"
  commit = false
  rss = false
  comments = false
  readingTime = false
  wordCount = false
  useHLJS = false
  socialShare = false
  delayDisqus = false
  showRelatedPosts = false


[Author]
  github = "Richyyl"
  twitter = "Richyyl"

[[menu.main]]
  name = "Posts"
  url = "post/"
  logo = "img/avatar.png"
  weight = 2

[[menu.main]]
  name = "About"
  logo = "img/avatar.png"
  url = "page/about"
  weight = 3
