baseurl = "rlouden.netlify.com/"
languageCode = "en-us"
title = "A blog to document my foray into analytics and machine learning"
theme = "beautifulhugo"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"

[[social_icons]]
id = "github"
url = "https://github.com/Richyyl"
title = "GitHub"
icon = "fab fa-github"

[[social_icons]]
id = "twitter"
url = "https://twitter.com/Richyyl"
title = "Twitter"
icon = "fab fa-twitter"